# Generated by Django 6.0.3 on 2026-06-28 02:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_link', models.CharField(max_length=1000)),
                ('entry_title', models.CharField(blank=True, max_length=500)),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_entries', to='feeds.feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-read_at'],
                'indexes': [models.Index(fields=['user', 'feed'], name='feeds_reada_user_id_06e37a_idx')],
                'unique_together': {('user', 'feed', 'entry_link')},
            },
        ),
    ]
