# Generated by Django 6.0.3 on 2026-06-28 03:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def migrate_readarticle_to_feeditem(apps, schema_editor):
    """Carry read-state from the old ReadArticle table into FeedItem.

    For each ReadArticle, ensure a FeedItem exists with is_read=True and
    read_at copied over. The next dashboard load will refresh titles/links
    from the live feed via update_or_create, so existing entry_id matches
    will be reused (preserving is_read).
    """
    ReadArticle = apps.get_model("feeds", "ReadArticle")
    FeedItem = apps.get_model("feeds", "FeedItem")
    for ra in ReadArticle.objects.all():
        feeditem, created = FeedItem.objects.get_or_create(
            feed=ra.feed,
            entry_id=ra.entry_link,
            defaults={
                "title": ra.entry_title,
                "link": ra.entry_link,
                "is_read": True,
                "read_at": ra.read_at,
            },
        )
        if not created and not feeditem.is_read:
            feeditem.is_read = True
            feeditem.read_at = ra.read_at
            feeditem.save(update_fields=["is_read", "read_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_readarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=1000)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('link', models.URLField(blank=True, max_length=1000)),
                ('summary', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published', '-fetched_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='readarticle',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='readarticle',
            name='feeds_reada_user_id_06e37a_idx',
        ),
        migrations.AddField(
            model_name='feed',
            name='last_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='feeds.feed'),
        ),
        migrations.RemoveField(
            model_name='readarticle',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='readarticle',
            name='user',
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['feed', 'is_read'], name='feeds_feedi_feed_id_ffccd1_idx'),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['feed', '-published'], name='feeds_feedi_feed_id_892e9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feeditem',
            unique_together={('feed', 'entry_id')},
        ),
        migrations.RunPython(
            code=migrate_readarticle_to_feeditem,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name='ReadArticle',
        ),
    ]
