# Generated by Django 3.1.3 on 2021-01-31 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201224_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='body',
        ),
    ]
