# Generated by Django 3.1.3 on 2020-11-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_note_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='subject',
            new_name='title',
        ),
    ]
