# Generated by Django 5.2 on 2025-04-14 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_note_id_alter_post_id_alter_tag_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
