# Generated by Django 5.2.6 on 2026-03-07 19:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_note_id_alter_post_id_alter_tag_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="blog.tag"),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="tag",
            name="tag_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="tag_name",
            field=models.CharField(default="NULL", max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
