# Generated by Django 6.0.3 on 2026-03-08 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_inlineimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="inlineimage",
            name="session_key",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="inlineimage",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inline_images",
                to="blog.post",
            ),
        ),
    ]
