# Generated by Django 6.0.7 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="inlineimage",
            name="alt_text",
            field=models.CharField(default="Blog image", max_length=255),
        ),
    ]
