# Generated by Django 6.0.7 on 2026-07-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_inlineimage_alt_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="inline_image_alt_text",
            field=models.CharField(
                blank=True,
                default="Blog image",
                help_text="Default alt text assigned to every image in this post.",
                max_length=255,
            ),
        ),
    ]
