# Generated by Django 6.0.7 on 2026-07-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_post_inline_image_alt_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="inline_image_alt_text",
        ),
    ]
