# Generated by Django 6.0.7 on 2026-07-21 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_remove_post_inline_image_alt_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gratitude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gratitude_text", models.TextField(verbose_name="Gratitude Text")),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gratitudes_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "target",
                    models.ManyToManyField(
                        blank=True,
                        related_name="gratitudes_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Target Users",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gratitude",
                "verbose_name_plural": "Gratitudes",
                "ordering": ["-created_date"],
            },
        ),
    ]
