# Generated by Django 3.1.3 on 2020-11-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='static', upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
