# Generated by Django 6.0.7 on 2026-07-22 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_create_feature_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagementCommandRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command_name", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("details", models.TextField(blank=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("duration_seconds", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name": "Management Command Run",
                "verbose_name_plural": "Management Command Runs",
                "ordering": ["-started_at"],
            },
        ),
    ]
