# Generated by Django 3.1.3 on 2020-11-22 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201122_0653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
