# Generated by Django 3.2.2 on 2021-06-17 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtown', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='author',
        ),
    ]
