# Generated by Django 6.0.7 on 2026-07-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemdAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("can_view_systemd", "Can view host systemd status"),
                    (
                        "can_manage_systemd",
                        "Can start/stop/restart host systemd services",
                    ),
                ],
                "managed": False,
            },
        ),
    ]
