# Generated by Django 3.1.3 on 2020-12-24 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Symptom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(verbose_name="symptoms")),
            ],
        ),
        migrations.CreateModel(
            name="HealthEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("when", models.DateTimeField(auto_now_add=True)),
                (
                    "temperature",
                    models.FloatField(
                        blank=True, null=True, verbose_name="temperatures"
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("feels_rating", models.IntegerField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "symptoms",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="symptoms",
                        to="healthstats.Symptom",
                    ),
                ),
            ],
        ),
    ]
