# Generated by Django 3.1.3 on 2020-12-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthstats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthevent",
            name="symptoms",
            field=models.ManyToManyField(
                blank=True, related_name="symptoms", to="healthstats.Symptom"
            ),
        ),
    ]
