# Generated by Django 3.1.3 on 2020-12-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthstats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthevent',
            old_name='what',
            new_name='event_type',
        ),
        migrations.AddField(
            model_name='healthevent',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthevent',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='healthevent',
            name='when',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
