# Generated by Django 3.1.3 on 2021-01-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthstats", "0005_auto_20201224_1657"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthevent",
            name="feels_rating",
            field=models.IntegerField(
                blank=True,
                help_text="Overall feelings impression. enter a number between 0 and 10, 0 is bad, 10 is good",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthevent",
            name="note",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Are there any notes related to this event?",
            ),
        ),
        migrations.AlterField(
            model_name="healthevent",
            name="symptoms",
            field=models.ManyToManyField(
                blank=True,
                help_text="hold command or ctrl key to select more than one symptom",
                related_name="symptoms",
                to="healthstats.Symptom",
            ),
        ),
        migrations.AlterField(
            model_name="healthevent",
            name="temperature",
            field=models.FloatField(
                blank=True,
                help_text="temperature in Farenheit please, 1 or more decimal places",
                null=True,
                verbose_name="what is your temperature right now",
            ),
        ),
    ]
