# Generated by Django 3.1.6 on 2021-03-17 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("healthstats", "0008_auto_20210308_0248"),
    ]

    operations = [
        migrations.AlterField(
            model_name="symptom",
            name="slug",
            field=models.SlugField(
                help_text="Enter the name in with hyphens instead of spaces, like 'my-symptom-name'",
                max_length=200,
                unique=True,
                verbose_name="Symptom name",
            ),
        ),
        migrations.CreateModel(
            name="HeartRate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("value", models.FloatField()),
                (
                    "author",
                    models.ForeignKey(
                        default=4,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
