# Generated by Django 3.1.6 on 2021-03-21 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("healthstats", "0011_oxygendata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healthevent",
            name="feels_rating",
        ),
    ]
