# Generated by Django 3.1.6 on 2021-03-22 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthstats', '0012_remove_healthevent_feels_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleHealthUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_data_xml', models.FileField(upload_to='apple_health_xml')),
                ('author', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
