# Generated by Django 3.2.2 on 2021-06-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthstats', '0013_applehealthupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applehealthupload',
            name='health_data_xml',
            field=models.FileField(upload_to='apple_health_xml/'),
        ),
    ]
