# Generated by Django 3.2.2 on 2021-06-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthstats", "0014_alter_applehealthupload_health_data_xml"),
    ]

    operations = [
        migrations.AddField(
            model_name="applehealthupload",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
    ]
