# Generated by Django 5.0.2 on 2024-02-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthstats", "0019_bloodpressure"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodpressure",
            name="position",
            field=models.CharField(
                choices=[
                    ("sitting", "Sitting"),
                    ("laying down", "Laying Down"),
                    ("standing", "Standing"),
                ],
                default="sitting",
                max_length=15,
            ),
        ),
    ]
