# Generated by Django 6.0.7 on 2026-07-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthstats", "0023_remove_applehealthupload_csv_data_dir_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applehealthupload",
            name="csv_data_dir",
            field=models.CharField(
                blank=True,
                help_text="Legacy path used for imported CSV data",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applehealthupload",
            name="is_imported",
            field=models.BooleanField(
                default=False,
                help_text="Legacy flag for whether the import has completed",
            ),
        ),
        migrations.AddField(
            model_name="applehealthupload",
            name="is_processed",
            field=models.BooleanField(
                default=False,
                help_text="Legacy flag for whether the import has been processed",
            ),
        ),
    ]
